export const members = [
    {
        id: 1,
        name: "Miron Chmielewski",
        position: "Prezes Zarządu Fundacji",
        description: "Z wyksztacenia PETagog, wieloletni działacz na rzecz zwierząt. Swoją przygodę ze zwierzętami zaczął jeszcze na studiach, a\xa0miłość do zwierząt ewoluowała w\xa0nim, by w\xa0końcu stać się jednym z\xa0głównych celów jego życia.",
        email: "miron.chmielewski@matuzalki.pl",
        linkToPhone: "+48518756665",
        phone: "518 756 665",
        img: "Miron",
    },
    {
        id: 2,
        name: "Barbara Laskowska",
        position: "Sekretarz, V-ce Prezes Zarządu Fundacji",
        description: "Z\xa0wykształcenia PETagog. Adoptowała z\xa0Ośrodka starszego psa i\xa0tak już została. Absolutnie zaangażowana w\xa0psie sprawy, pełna sił do działania. Stanowi dla Fundacji swoiste okno na Wielkopolskę (z\xa0racji zamieszkania).",
        email: "barbara.laskowska@matuzalki.pl",
        img: "Basia",
    },
    {
        id: 3,
        name: "Ela Platt",
        position: "Skarbnik, V-ce Prezes Zarządu Fundacji",
        description: "Lekarz medycyny, absolutnie uzależniona od pomagania zwierzętom, szczególnie tym starym i\xa0niechcianym. Uratowała i\xa0postawiła na nogi setki psów w\xa0potrzebie, niesamowicie doświadczona w\xa0opiece nad zwierzętami.",
        email: "ela.platt@matuzalki.pl",
        linkToPhone: "+48519499344",
        phone: "519 499 344",
        img: "Ela",
    },
    {
        id: 4,
        name: "Joanna Szwed",
        position: "Przewodnicząca Rady Fundacji",
        description: "Z wyksztacenia ekonomista, analityk. Najbliższy jej sercu jest los kotów. Karmicielka i\xa0dobra dusza, szczególne tych wolnożyjących na terenie Wrocławia. Od lat walczy o\xa0ich bezpieczeństwo i\xa0godne życie.",
        img: "Joasia",
    },
    {
        id: 5,
        name: "Asia Węgrzynowicz",
        position: "Członek Rady Fundacji",
        description: "Pani technik WETerynarii, z\xa0nami od zawsze, pomaga w\xa0działaniach Fundacji. Psiara pełną gębą. Asia pracuje w\xa0Gabinecie weterynaryjnym ORZ KĄTNA, który sprawuje opiekę nad naszym stadem.",
        email: "joanna.wegrzynowicz@matuzalki.pl",
        img: "Asia",
    },
    {
        id: 6,
        name: "Magda Mrówczyńska",
        position: "Członek Rady Fundacji",
        description: 'Z wyksztacenia PSYcholog, prawdziwy mistrz organizacji . W\xa0pracy na rzecz Fundacji kieruje się mottem: "...problemy należy rozwiązywać, a\xa0nie tworzyć..." Odpowiedzialna za sprawy organizacyjne i\xa0prawne.',
        img: "Magda",
    },
]